# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlVaultLogin < Formula
  desc "kubectl-vault-login"
  homepage "https://github.com/FalcoSuessgott/kubectl-vault-login"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalcoSuessgott/kubectl-vault-login/releases/download/v0.0.2/kubectl-vault-login_Darwin_x86_64.tar.gz"
      sha256 "057153dde33ab391e2c5a28a01659c37d93e307eea60aa5dd0cd69eef5f91df9"

      def install
        bin.install "kubectl-vault-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalcoSuessgott/kubectl-vault-login/releases/download/v0.0.2/kubectl-vault-login_Darwin_arm64.tar.gz"
      sha256 "1f209a2a4a0f2915753140abd807bad16ff52b48b5a68733f65924fae5d0681a"

      def install
        bin.install "kubectl-vault-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/kubectl-vault-login/releases/download/v0.0.2/kubectl-vault-login_Linux_x86_64.tar.gz"
        sha256 "6ee0c5ae95fef1138d7887ea15e0613159121459e7929a0d9b0ff9c012788fb9"

        def install
          bin.install "kubectl-vault-login"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/kubectl-vault-login/releases/download/v0.0.2/kubectl-vault-login_Linux_arm64.tar.gz"
        sha256 "9b3e92f35f89bc0c99204f51e3e0ba1613e51d7f159300bebb5ef10a078cfefb"

        def install
          bin.install "kubectl-vault-login"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-vault-login"
  end
end
