# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtmpl < Formula
  desc "mdtpl"
  homepage "https://github.com/FalcoSuessgott/mdtmpl"
  version "0.2.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.2.3/mdtmpl_Darwin_x86_64.tar.gz"
      sha256 "33e3ed17a9730fa2af1ebf6e68c870d96a0d2d07b7a6396bf1fca0c9b7c9ff63"

      def install
        bin.install "mdtmpl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.2.3/mdtmpl_Darwin_arm64.tar.gz"
      sha256 "d3e0ec586edaf265abc4b9c38d2e36ff5eded72b3769e770c1f8ec31c311bb72"

      def install
        bin.install "mdtmpl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.2.3/mdtmpl_Linux_x86_64.tar.gz"
      sha256 "f07dbb48ca982b66668e017743327a785d963c6a7a3b11a697ce74c28c32f179"
      def install
        bin.install "mdtmpl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.2.3/mdtmpl_Linux_arm64.tar.gz"
      sha256 "a3f5d59ef7b2a7f6c2c665d732d8cdc2ea6c165916ddf6da81965124ac8f3ebc"
      def install
        bin.install "mdtmpl"
      end
    end
  end

  test do
    system "#{bin}/mdtmpl"
  end
end
