# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtmpl < Formula
  desc "mdtpl"
  homepage "https://github.com/FalcoSuessgott/mdtmpl"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.0.6/mdtmpl_Darwin_x86_64.tar.gz"
      sha256 "276000ece0afc5c97fb5569e6dbcc160abdf7bffce9201c65db098726d70e137"

      def install
        bin.install "mdtmpl"
      end
    end
    on_arm do
      url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.0.6/mdtmpl_Darwin_arm64.tar.gz"
      sha256 "b7ddca830df586ebb969b384166c44818a159c9483591a614a13039342b8e1d7"

      def install
        bin.install "mdtmpl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.0.6/mdtmpl_Linux_x86_64.tar.gz"
        sha256 "5e48d0db17610a62b13050bc36ab8df0ea98bfe4ce18fdcb015e73a05aa9defd"

        def install
          bin.install "mdtmpl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/mdtmpl/releases/download/v0.0.6/mdtmpl_Linux_arm64.tar.gz"
        sha256 "13c70b1e1cb7f5c955eb46a666dc8295873ea8fcffa6cca4b1230afd64b04431"

        def install
          bin.install "mdtmpl"
        end
      end
    end
  end

  test do
    system "#{bin}/mdtmpl"
  end
end
