# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vkv < Formula
  desc "vkv"
  homepage "https://falcosuessgott.github.io/vkv/"
  version "0.9.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.9.3/vkv_Darwin_x86_64.tar.gz"
      sha256 "d2fa7f8e6d40f97451ec0f6e47cb6631101c39e6adba4f301c722e482dd7142d"

      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.9.3/vkv_Darwin_arm64.tar.gz"
      sha256 "ddd625f6e2f751fbe3b55325eff4a52077a10136626021ceffdaa8889e521456"

      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.9.3/vkv_Linux_x86_64.tar.gz"
      sha256 "646ca9390f96210a065b33bfed62215c8a6567d41452e68898cb83dca9757682"
      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.9.3/vkv_Linux_arm64.tar.gz"
      sha256 "a5d80ce35eb96408d67be22ea6ec8293cfd52219ee1771ffa049fbf9d980c27d"
      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/vkv version"
  end
end
