# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vkv < Formula
  desc "vkv"
  homepage "https://falcosuessgott.github.io/vkv/"
  version "0.8.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.8.5/vkv_Darwin_x86_64.tar.gz"
      sha256 "f7045a9ad2e0eb555be9fc3583cfac747cdda5f61e5fef7659a770cebb9d1611"

      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.8.5/vkv_Darwin_arm64.tar.gz"
      sha256 "b4184b41c7982dcee87c1516ab318d0d5b509da9a998d1684c2fc860a559e1f6"

      def install
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.8.5/vkv_Linux_x86_64.tar.gz"
        sha256 "d69cce710afe0b859c7aefdafa9c46370f064b42f8023927e2765e7e3b1e4d93"

        def install
          bin.install "vkv"
          bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
          (bash_completion/"vkv").write bash_output
          zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
          (zsh_completion/"vkv").write zsh_output
          fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
          (fish_completion/"vkv.fish").write fish_output
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FalcoSuessgott/vkv/releases/download/v0.8.5/vkv_Linux_arm64.tar.gz"
        sha256 "d5786bb8976c0ddc12e97c2654adfcfd9552fedb37b99647a6619c7d0ee31eff"

        def install
          bin.install "vkv"
          bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
          (bash_completion/"vkv").write bash_output
          zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
          (zsh_completion/"vkv").write zsh_output
          fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
          (fish_completion/"vkv.fish").write fish_output
        end
      end
    end
  end

  test do
    system "#{bin}/vkv version"
  end
end
