# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vkv < Formula
  desc "vkv"
  homepage "https://falcosuessgott.github.io/vkv/"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v1.0.0/vkv_Darwin_x86_64.tar.gz"
      sha256 "4a7c665b0ab42f082543d8c61d62411595857e5bab8d96db41df4a43a2869865"

      define_method(:install) do
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v1.0.0/vkv_Darwin_arm64.tar.gz"
      sha256 "bd3ed11c1c2526847d8741d3529f2e8ca9e9d3c87adf04a8b8016c91076ece87"

      define_method(:install) do
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v1.0.0/vkv_Linux_x86_64.tar.gz"
      sha256 "a7378c15d9c0f740bdb9f5322f553da0529eaf67b694f88d623eae2d44ac38f4"
      define_method(:install) do
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FalcoSuessgott/vkv/releases/download/v1.0.0/vkv_Linux_arm64.tar.gz"
      sha256 "1c00549ab6dacc84f563b02aa3d840d4c614d71b7ab068d86aacddf2d986869e"
      define_method(:install) do
        bin.install "vkv"
        bash_output = Utils.safe_popen_read(bin/"vkv", "completion", "bash")
        (bash_completion/"vkv").write bash_output
        zsh_output = Utils.safe_popen_read(bin/"vkv", "completion", "zsh")
        (zsh_completion/"vkv").write zsh_output
        fish_output = Utils.safe_popen_read(bin/"vkv", "completion", "fish")
        (fish_completion/"vkv.fish").write fish_output
      end
    end
  end

  test do
    system "#{bin}/vkv version"
  end
end
